declare class CreateRoleUI extends egret.DisplayObjectContainer {
    private m_ServerData;
    private m_Textures;
    constructor(serverData: GameServerDescData);
    private m_IsRandom;
    private m_TweenList;
    private m_Random;
    private m_GoBtn;
    private m_TextField;
    private m_CurImgIndex;
    private m_Index;
    private m_Job;
    private m_Sex;
    private timeLabel;
    private sex1;
    private sex2;
    private sel1;
    private sel2;
    private roleGroup0;
    private roleGroup1;
    private roleImg0;
    private roleImg1;
    private mSelImg;
    private time;
    private m_CreateThm1();
    private AddSelGroup();
    private onAddToStage(event);
    private _DoFocus();
    private UpdateIndex(value);
    private DoRandom();
    private _DoRandom();
    private m_CheckName;
    private m_CheckIndex;
    private _DoGo();
    private SendPoint(point);
    private _Go(data);
    private _DoRandomName(data);
    private Select(index);
    private UpdateSel();
    private _LoadTexture(index);
    private _Loaded(obj, name);
    private Close();
    private m_LastTime;
    private AddTween(target, prop, duration);
    private Update(timeStamp);
    static circOut(t: number): number;
    private static SetDownState(obj);
}
